### ISSUE TITLE
Message original sender

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/mrc#156]
When message is being sent by a provider, the original message sender msa should get stored.

**Comment by iamianM** [comment]
Hey @enddynayn I was just messing around with this and wondering the same thing. If alice is a provider of like 4 msa_id's it just seems to use the most recently delegated id. How would it decide though? Alice is signing the Messages.add transactions in order to pay the fees, so I don't see where the delegator is involved. Should the delegator by signing something?

**Comment by enddynayn** [comment]
Let's say that Alice is a provider to Bob. In other words, Bob is a delegator and Alice is the delegate.
If Alice wants to sends a message on behalf of Bob the second parameter of Messages.add, on_behalf, is populated with Bobs MsaId. We can verify that the message is valid, offchain, by checking that Alice was indeed a provider to Bob.

**Comment by iamianM** [comment]
@enddynayn I only see schemaId and message as parameters for Messages.add
I'm confused as to what you mean by the second parameter `on_behalf`

**Comment by saraswatpuneet** [comment]
@enddynayn  you mean if on_behalf is provided, do we need to store if message was sent on behalf of "this msa _id"? to be clear
