### ISSUE TITLE
[MRC] Benchmark runs error out when used mock object

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/mrc#80]
When using a Mock Object for loosely bounded pallets then benchmarks are not setup correctly and can not execute the mock object from Test context.

We need to find a way to fix this issue.
Example:
If you run benchmarks on messages it will error out since it can not detect the message source account due to the Test mock not being maybe accessible from benchmark?

**Comment by shannonwells** [comment]
The benchmark is definitely using the runtime config in runtime/src/lib.rs, which is to use Msa as the AccountProvider.

I've tried a number of different ways to understand why it is ignoring the config in messages/src/mock.rs but it always uses the above one.  We are following exactly the recommended method for implementing and using the trait via a config.

I've tried:
* ensuring that all types refer only to what is configured, everywhere in the config setup
* implementing a toy trait in another pallet and another benchmark
* looking for signs of a red herring (i.e. some other call that is causing the issue).

I will check in what I have in a branch because it contains fixes so that the benchmarks will actually build.
